name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  BOOST_VERSION: 1.83.0
  BOOST_PATH: ${{github.workspace}}/boost/boost

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGLFW_BUILD_WAYLAND=OFF -DGLFW_BUILD_X11=OFF

    - name: Build
      run: cmake --build ${{github.workspace}}/build --target engine_test --config ${{env.BUILD_TYPE}}

    - name: Run unit tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
